/bin/java_vm
/bin/javaws
/bin/jcontrol
/bin/keytool
/bin/orbd
/bin/pack200
/bin/policytool
/bin/rmid
/bin/rmiregistry
/bin/servertool
/bin/tnameserv
/lib/charsets.jar
/lib/classlist
/lib/deploy.jar
/lib/deploy/ffjcext.zip
/lib/deploy/java-icon.ico
/lib/deploy/messages.properties
/lib/deploy/messages_de.properties
/lib/deploy/messages_es.properties
/lib/deploy/messages_fr.properties
/lib/deploy/messages_it.properties
/lib/deploy/messages_ja.properties
/lib/deploy/messages_ko.properties
/lib/deploy/messages_sv.properties
/lib/deploy/messages_zh_CN.properties
/lib/deploy/messages_zh_HK.properties
/lib/deploy/messages_zh_TW.properties
/lib/deploy/splash.jpg
/lib/desktop/applications/sun-java.desktop
/lib/desktop/applications/sun-javaws.desktop
/lib/desktop/applications/sun_java.desktop
/lib/desktop/icons/HighContrast/16x16/apps/sun-java.png
/lib/desktop/icons/HighContrast/16x16/apps/sun-javaws.png
/lib/desktop/icons/HighContrast/16x16/apps/sun-jcontrol.png
/lib/desktop/icons/HighContrast/16x16/mimetypes/gnome-mime-application-x-java-archive.png
/lib/desktop/icons/HighContrast/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png
/lib/desktop/icons/HighContrast/16x16/mimetypes/gnome-mime-text-x-java.png
/lib/desktop/icons/HighContrast/48x48/apps/sun-java.png
/lib/desktop/icons/HighContrast/48x48/apps/sun-javaws.png
/lib/desktop/icons/HighContrast/48x48/apps/sun-jcontrol.png
/lib/desktop/icons/HighContrast/48x48/mimetypes/gnome-mime-application-x-java-archive.png
/lib/desktop/icons/HighContrast/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png
/lib/desktop/icons/HighContrast/48x48/mimetypes/gnome-mime-text-x-java.png
/lib/desktop/icons/HighContrastInverse/16x16/apps/sun-java.png
/lib/desktop/icons/HighContrastInverse/16x16/apps/sun-javaws.png
/lib/desktop/icons/HighContrastInverse/16x16/apps/sun-jcontrol.png
/lib/desktop/icons/HighContrastInverse/16x16/mimetypes/gnome-mime-application-x-java-archive.png
/lib/desktop/icons/HighContrastInverse/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png
/lib/desktop/icons/HighContrastInverse/16x16/mimetypes/gnome-mime-text-x-java.png
/lib/desktop/icons/HighContrastInverse/48x48/apps/sun-java.png
/lib/desktop/icons/HighContrastInverse/48x48/apps/sun-javaws.png
/lib/desktop/icons/HighContrastInverse/48x48/apps/sun-jcontrol.png
/lib/desktop/icons/HighContrastInverse/48x48/mimetypes/gnome-mime-application-x-java-archive.png
/lib/desktop/icons/HighContrastInverse/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png
/lib/desktop/icons/HighContrastInverse/48x48/mimetypes/gnome-mime-text-x-java.png
/lib/desktop/icons/LowContrast/16x16/apps/sun-java.png
/lib/desktop/icons/LowContrast/16x16/apps/sun-javaws.png
/lib/desktop/icons/LowContrast/16x16/apps/sun-jcontrol.png
/lib/desktop/icons/LowContrast/16x16/mimetypes/gnome-mime-application-x-java-archive.png
/lib/desktop/icons/LowContrast/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png
/lib/desktop/icons/LowContrast/16x16/mimetypes/gnome-mime-text-x-java.png
/lib/desktop/icons/LowContrast/48x48/apps/sun-java.png
/lib/desktop/icons/LowContrast/48x48/apps/sun-javaws.png
/lib/desktop/icons/LowContrast/48x48/apps/sun-jcontrol.png
/lib/desktop/icons/LowContrast/48x48/mimetypes/gnome-mime-application-x-java-archive.png
/lib/desktop/icons/LowContrast/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png
/lib/desktop/icons/LowContrast/48x48/mimetypes/gnome-mime-text-x-java.png
/lib/desktop/icons/hicolor/16x16/apps/sun-java.png
/lib/desktop/icons/hicolor/16x16/apps/sun-javaws.png
/lib/desktop/icons/hicolor/16x16/apps/sun-jcontrol.png
/lib/desktop/icons/hicolor/16x16/mimetypes/gnome-mime-application-x-java-archive.png
/lib/desktop/icons/hicolor/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png
/lib/desktop/icons/hicolor/16x16/mimetypes/gnome-mime-text-x-java.png
/lib/desktop/icons/hicolor/48x48/apps/sun-java.png
/lib/desktop/icons/hicolor/48x48/apps/sun-javaws.png
/lib/desktop/icons/hicolor/48x48/apps/sun-jcontrol.png
/lib/desktop/icons/hicolor/48x48/mimetypes/gnome-mime-application-x-java-archive.png
/lib/desktop/icons/hicolor/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png
/lib/desktop/icons/hicolor/48x48/mimetypes/gnome-mime-text-x-java.png
/lib/desktop/mime/packages/x-java-archive.xml
/lib/desktop/mime/packages/x-java-jnlp-file.xml
/lib/ext/dnsns.jar
/lib/ext/localedata.jar
/lib/ext/meta-index
/lib/ext/sunjce_provider.jar
/lib/ext/sunpkcs11.jar
/lib/i386/jvm.cfg
/lib/i386/libJdbcOdbc.so
/lib/i386/libattach.so
/lib/i386/libdeploy.so
/lib/i386/libdt_socket.so
/lib/i386/libhprof.so
/lib/i386/libinstrument.so
/lib/i386/libj2gss.so
/lib/i386/libj2pcsc.so
/lib/i386/libj2pkcs11.so
/lib/i386/libjaas_unix.so
/lib/i386/libjava_crw_demo.so
/lib/i386/libjavaplugin_jni.so
/lib/i386/libjavaplugin_nscp.so
/lib/i386/libjavaplugin_nscp_gcc29.so
/lib/i386/libjdwp.so
/lib/i386/libjsdt.so
/lib/i386/libjsound.so
/lib/i386/libjsoundalsa.so
/lib/i386/libmanagement.so
/lib/i386/libnpt.so
/lib/i386/librmi.so
/lib/i386/libsaproc.so
/lib/i386/libunpack.so
/lib/i386/server/Xusage.txt
/lib/i386/server/classes.jsa
/lib/i386/server/libjvm.so
/lib/javaws.jar
/lib/jce.jar
/lib/jexec
/lib/jsse.jar
/lib/jvm.hprof.txt
/lib/management-agent.jar
/lib/management/jmxremote.access
/lib/management/jmxremote.password.template
/lib/management/management.properties
/lib/management/snmp.acl.template
/lib/meta-index
/lib/plugin.jar
/lib/resources.jar
/lib/rt.jar
/lib/security/US_export_policy.jar
/lib/security/cacerts
/lib/security/local_policy.jar
/lib/servicetag/jdk_header.png
/lib/sound.properties
/plugin/desktop/sun_java.desktop
/plugin/desktop/sun_java.png
/plugin/i386/ns7-gcc29/libjavaplugin_oji.so
/plugin/i386/ns7/libjavaplugin_oji.so
