/lib/cmm/CIEXYZ.pf
/lib/cmm/GRAY.pf
/lib/cmm/LINEAR_RGB.pf
/lib/cmm/PYCC.pf
/lib/cmm/sRGB.pf
/lib/flavormap.properties
/lib/fontconfig.RedHat.2.1.bfc
/lib/fontconfig.RedHat.2.1.properties.src
/lib/fontconfig.RedHat.3.bfc
/lib/fontconfig.RedHat.3.properties.src
/lib/fontconfig.RedHat.4.bfc
/lib/fontconfig.RedHat.4.properties.src
/lib/fontconfig.RedHat.bfc
/lib/fontconfig.RedHat.properties.src
/lib/fontconfig.SuSE.bfc
/lib/fontconfig.SuSE.properties.src
/lib/fontconfig.Sun.bfc
/lib/fontconfig.Sun.properties.src
/lib/fontconfig.Turbo.bfc
/lib/fontconfig.Turbo.properties.src
/lib/fontconfig.bfc
/lib/fontconfig.properties.src
/lib/fonts/LucidaBrightDemiBold.ttf
/lib/fonts/LucidaBrightDemiItalic.ttf
/lib/fonts/LucidaBrightItalic.ttf
/lib/fonts/LucidaBrightRegular.ttf
/lib/fonts/LucidaSansDemiBold.ttf
/lib/fonts/LucidaSansRegular.ttf
/lib/fonts/LucidaTypewriterBold.ttf
/lib/fonts/LucidaTypewriterRegular.ttf
/lib/fonts/fonts.dir
/lib/i386/headless/libmawt.so
/lib/i386/libawt.so
/lib/i386/libdcpr.so
/lib/i386/libfontmanager.so
/lib/i386/libjawt.so
/lib/i386/libjpeg.so
/lib/i386/libkcms.so
/lib/i386/libmlib_image.so
/lib/i386/libsplashscreen.so
/lib/i386/libt2k.so
/lib/i386/xawt/libmawt.so
/lib/images/cursors/cursors.properties
/lib/images/cursors/invalid32x32.gif
/lib/images/cursors/motif_CopyDrop32x32.gif
/lib/images/cursors/motif_CopyNoDrop32x32.gif
/lib/images/cursors/motif_LinkDrop32x32.gif
/lib/images/cursors/motif_LinkNoDrop32x32.gif
/lib/images/cursors/motif_MoveDrop32x32.gif
/lib/images/cursors/motif_MoveNoDrop32x32.gif
/lib/images/icons/sun-java.png
/lib/images/icons/sun-java_HighContrast.png
/lib/images/icons/sun-java_HighContrastInverse.png
/lib/images/icons/sun-java_LowContrast.png
/lib/oblique-fonts/LucidaSansDemiOblique.ttf
/lib/oblique-fonts/LucidaSansOblique.ttf
/lib/oblique-fonts/LucidaTypewriterBoldOblique.ttf
/lib/oblique-fonts/LucidaTypewriterOblique.ttf
/lib/oblique-fonts/fonts.dir
/lib/psfont.properties.ja
/lib/psfontj2d.properties
